2020-06-06T21:20:51.712465+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=django-ocr-backend.herokuapp.com request_id=03657881-a258-4211-94f4-5e84fa69ef37 fwd="24.18.236.208" dyno= connect= service= status=503 bytes= protocol=https
2020-06-06T21:23:14.000000+00:00 app[api]: Build started by user josephvcardenas@gmail.com
2020-06-06T21:23:46.195419+00:00 app[api]: Deploy 26984f46 by user josephvcardenas@gmail.com
2020-06-06T21:23:46.195419+00:00 app[api]: Release v43 created by user josephvcardenas@gmail.com
2020-06-06T21:23:46.541317+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-06T21:23:52.791244+00:00 heroku[web.1]: Starting process with command `gunicorn django-ocr-backend:application --log-file -`
2020-06-06T21:23:55.021051+00:00 app[web.1]: [2020-06-06 21:23:55 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-06-06T21:23:55.021596+00:00 app[web.1]: [2020-06-06 21:23:55 +0000] [4] [INFO] Listening at: http://0.0.0.0:51672 (4)
2020-06-06T21:23:55.021690+00:00 app[web.1]: [2020-06-06 21:23:55 +0000] [4] [INFO] Using worker: sync
2020-06-06T21:23:55.025267+00:00 app[web.1]: [2020-06-06 21:23:55 +0000] [9] [INFO] Booting worker with pid: 9
2020-06-06T21:23:55.028832+00:00 app[web.1]: Failed to find attribute 'application' in 'django-ocr-backend'.
2020-06-06T21:23:55.028949+00:00 app[web.1]: [2020-06-06 21:23:55 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-06-06T21:23:55.055113+00:00 app[web.1]: [2020-06-06 21:23:55 +0000] [4] [INFO] Shutting down: Master
2020-06-06T21:23:55.055199+00:00 app[web.1]: [2020-06-06 21:23:55 +0000] [4] [INFO] Reason: App failed to load.
2020-06-06T21:23:55.114882+00:00 heroku[web.1]: Process exited with status 4
2020-06-06T21:23:55.150595+00:00 heroku[web.1]: State changed from starting to crashed
2020-06-06T21:24:01.000000+00:00 app[api]: Build succeeded
2020-06-06T21:28:36.435964+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=django-ocr-backend.herokuapp.com request_id=4836e32b-2a60-4d53-afa2-8cd2c668a914 fwd="24.18.236.208" dyno= connect= service= status=503 bytes= protocol=https
2020-06-06T21:30:12.602191+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-06T21:30:18.645823+00:00 heroku[web.1]: Starting process with command `gunicorn django-ocr-backend:application --log-file -`
2020-06-06T21:30:20.588686+00:00 app[web.1]: [2020-06-06 21:30:20 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-06-06T21:30:20.589269+00:00 app[web.1]: [2020-06-06 21:30:20 +0000] [4] [INFO] Listening at: http://0.0.0.0:5002 (4)
2020-06-06T21:30:20.589383+00:00 app[web.1]: [2020-06-06 21:30:20 +0000] [4] [INFO] Using worker: sync
2020-06-06T21:30:20.592833+00:00 app[web.1]: [2020-06-06 21:30:20 +0000] [9] [INFO] Booting worker with pid: 9
2020-06-06T21:30:20.596598+00:00 app[web.1]: Failed to find attribute 'application' in 'django-ocr-backend'.
2020-06-06T21:30:20.596789+00:00 app[web.1]: [2020-06-06 21:30:20 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-06-06T21:30:20.625341+00:00 app[web.1]: [2020-06-06 21:30:20 +0000] [10] [INFO] Booting worker with pid: 10
2020-06-06T21:30:20.629066+00:00 app[web.1]: Failed to find attribute 'application' in 'django-ocr-backend'.
2020-06-06T21:30:20.629167+00:00 app[web.1]: [2020-06-06 21:30:20 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-06-06T21:30:20.657539+00:00 app[web.1]: Traceback (most recent call last):
2020-06-06T21:30:20.657541+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 202, in run
2020-06-06T21:30:20.657852+00:00 app[web.1]: self.manage_workers()
2020-06-06T21:30:20.657874+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
2020-06-06T21:30:20.658086+00:00 app[web.1]: self.spawn_workers()
2020-06-06T21:30:20.658103+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 617, in spawn_workers
2020-06-06T21:30:20.658466+00:00 app[web.1]: time.sleep(0.1 * random.random())
2020-06-06T21:30:20.658489+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2020-06-06T21:30:20.658694+00:00 app[web.1]: self.reap_workers()
2020-06-06T21:30:20.658696+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
2020-06-06T21:30:20.658906+00:00 app[web.1]: raise HaltServer(reason, self.APP_LOAD_ERROR)
2020-06-06T21:30:20.658966+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
2020-06-06T21:30:20.658968+00:00 app[web.1]: 
2020-06-06T21:30:20.658968+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-06T21:30:20.658969+00:00 app[web.1]: 
2020-06-06T21:30:20.658984+00:00 app[web.1]: Traceback (most recent call last):
2020-06-06T21:30:20.658985+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2020-06-06T21:30:20.659101+00:00 app[web.1]: sys.exit(run())
2020-06-06T21:30:20.659102+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
2020-06-06T21:30:20.659206+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2020-06-06T21:30:20.659208+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 228, in run
2020-06-06T21:30:20.659357+00:00 app[web.1]: super().run()
2020-06-06T21:30:20.659367+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
2020-06-06T21:30:20.659473+00:00 app[web.1]: Arbiter(self).run()
2020-06-06T21:30:20.659475+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
2020-06-06T21:30:20.659612+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2020-06-06T21:30:20.659615+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
2020-06-06T21:30:20.659788+00:00 app[web.1]: self.stop()
2020-06-06T21:30:20.659814+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
2020-06-06T21:30:20.659993+00:00 app[web.1]: time.sleep(0.1)
2020-06-06T21:30:20.659996+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2020-06-06T21:30:20.660136+00:00 app[web.1]: self.reap_workers()
2020-06-06T21:30:20.660138+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
2020-06-06T21:30:20.660341+00:00 app[web.1]: raise HaltServer(reason, self.APP_LOAD_ERROR)
2020-06-06T21:30:20.660365+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
2020-06-06T21:30:20.715219+00:00 heroku[web.1]: Process exited with status 1
2020-06-06T21:30:20.758918+00:00 heroku[web.1]: State changed from starting to crashed
2020-06-06T21:32:57.000000+00:00 app[api]: Build started by user josephvcardenas@gmail.com
2020-06-06T21:33:29.419397+00:00 app[api]: Deploy 36ae5e51 by user josephvcardenas@gmail.com
2020-06-06T21:33:29.419397+00:00 app[api]: Release v44 created by user josephvcardenas@gmail.com
2020-06-06T21:33:30.049105+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-06T21:33:36.142878+00:00 heroku[web.1]: Starting process with command `gunicorn django-ocr-backend:ocr --log-file -`
2020-06-06T21:33:38.304946+00:00 app[web.1]: [2020-06-06 21:33:38 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-06-06T21:33:38.305550+00:00 app[web.1]: [2020-06-06 21:33:38 +0000] [4] [INFO] Listening at: http://0.0.0.0:30355 (4)
2020-06-06T21:33:38.305671+00:00 app[web.1]: [2020-06-06 21:33:38 +0000] [4] [INFO] Using worker: sync
2020-06-06T21:33:38.309307+00:00 app[web.1]: [2020-06-06 21:33:38 +0000] [9] [INFO] Booting worker with pid: 9
2020-06-06T21:33:38.313195+00:00 app[web.1]: Failed to find attribute 'ocr' in 'django-ocr-backend'.
2020-06-06T21:33:38.313295+00:00 app[web.1]: [2020-06-06 21:33:38 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-06-06T21:33:38.342664+00:00 app[web.1]: [2020-06-06 21:33:38 +0000] [4] [INFO] Shutting down: Master
2020-06-06T21:33:38.342766+00:00 app[web.1]: [2020-06-06 21:33:38 +0000] [4] [INFO] Reason: App failed to load.
2020-06-06T21:33:38.397382+00:00 heroku[web.1]: Process exited with status 4
2020-06-06T21:33:38.430700+00:00 heroku[web.1]: State changed from starting to crashed
2020-06-06T21:33:44.000000+00:00 app[api]: Build succeeded
2020-06-06T21:33:48.584979+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=django-ocr-backend.herokuapp.com request_id=4443a917-689e-4516-8e75-3739cb9a78db fwd="24.18.236.208" dyno= connect= service= status=503 bytes= protocol=https
2020-06-06T21:35:38.000000+00:00 app[api]: Build started by user josephvcardenas@gmail.com
2020-06-06T21:36:13.893137+00:00 app[api]: Deploy 6a4d69db by user josephvcardenas@gmail.com
2020-06-06T21:36:13.893137+00:00 app[api]: Release v45 created by user josephvcardenas@gmail.com
2020-06-06T21:36:14.842457+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-06T21:36:22.250082+00:00 heroku[web.1]: Starting process with command `gunicorn django-ocr-backend --log-file -`
2020-06-06T21:36:27.044631+00:00 app[web.1]: [2020-06-06 21:36:27 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-06-06T21:36:27.045229+00:00 app[web.1]: [2020-06-06 21:36:27 +0000] [4] [INFO] Listening at: http://0.0.0.0:27220 (4)
2020-06-06T21:36:27.045306+00:00 app[web.1]: [2020-06-06 21:36:27 +0000] [4] [INFO] Using worker: sync
2020-06-06T21:36:27.050016+00:00 app[web.1]: [2020-06-06 21:36:27 +0000] [9] [INFO] Booting worker with pid: 9
2020-06-06T21:36:27.055313+00:00 app[web.1]: Failed to find attribute 'application' in 'django-ocr-backend'.
2020-06-06T21:36:27.055513+00:00 app[web.1]: [2020-06-06 21:36:27 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-06-06T21:36:27.097871+00:00 app[web.1]: [2020-06-06 21:36:27 +0000] [4] [INFO] Shutting down: Master
2020-06-06T21:36:27.097993+00:00 app[web.1]: [2020-06-06 21:36:27 +0000] [4] [INFO] Reason: App failed to load.
2020-06-06T21:36:27.239500+00:00 heroku[web.1]: Process exited with status 4
2020-06-06T21:36:27.315720+00:00 heroku[web.1]: State changed from starting to crashed
2020-06-06T21:36:29.000000+00:00 app[api]: Build succeeded
2020-06-06T21:36:42.238023+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=django-ocr-backend.herokuapp.com request_id=a7b4bee7-42e4-4584-bffa-212e9a8e22ef fwd="24.18.236.208" dyno= connect= service= status=503 bytes= protocol=https
2020-06-06T21:41:08.235473+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-06T21:41:14.088846+00:00 heroku[web.1]: Starting process with command `gunicorn django-ocr-backend --log-file -`
2020-06-06T21:41:16.243296+00:00 heroku[web.1]: Process exited with status 4
2020-06-06T21:41:16.285007+00:00 heroku[web.1]: State changed from starting to crashed
2020-06-06T21:41:16.037498+00:00 app[web.1]: [2020-06-06 21:41:16 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-06-06T21:41:16.038078+00:00 app[web.1]: [2020-06-06 21:41:16 +0000] [4] [INFO] Listening at: http://0.0.0.0:35238 (4)
2020-06-06T21:41:16.038196+00:00 app[web.1]: [2020-06-06 21:41:16 +0000] [4] [INFO] Using worker: sync
2020-06-06T21:41:16.041967+00:00 app[web.1]: [2020-06-06 21:41:16 +0000] [9] [INFO] Booting worker with pid: 9
2020-06-06T21:41:16.045580+00:00 app[web.1]: Failed to find attribute 'application' in 'django-ocr-backend'.
2020-06-06T21:41:16.045679+00:00 app[web.1]: [2020-06-06 21:41:16 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-06-06T21:41:16.048273+00:00 app[web.1]: [2020-06-06 21:41:16 +0000] [10] [INFO] Booting worker with pid: 10
2020-06-06T21:41:16.051591+00:00 app[web.1]: Failed to find attribute 'application' in 'django-ocr-backend'.
2020-06-06T21:41:16.051702+00:00 app[web.1]: [2020-06-06 21:41:16 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-06-06T21:41:16.175257+00:00 app[web.1]: [2020-06-06 21:41:16 +0000] [4] [INFO] Shutting down: Master
2020-06-06T21:41:16.175345+00:00 app[web.1]: [2020-06-06 21:41:16 +0000] [4] [INFO] Reason: App failed to load.
